### ISSUE TITLE
feature request: custom dev fee

### ISSUE THREAD

**Issue by ITwrx** [zawawawa/gatelessgate#11]
I would like to be able to designate a dev fee percentage of my choosing so i can contribute more than 1%, at least for a while.  Maybe keep the 1% as a minimum, as it's unreasonable and unsustainable otherwise. Proper funding is important so you can spend time improving and maintaining this miner. We need a competitive FLOSS miner.
thanks

**Comment by zawawawa** [comment]
I will consider this idea.
