### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by xsimiaox** [zawawawa/gatelessgate#13]
I love this miner, easy change pool. :'(

**Comment by aayanl** [comment]
only open source miner that came close to claymore and optiminer

**Comment by xsimiaox** [comment]
Yes :'(

**Comment by aaronsace** [comment]
https://github.com/zawawawa/GatelessGateSharp

**Comment by zawawawa** [comment]
Like @aaronsace pointed out, this project will be superseded by "Gateless Gate #."
